version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    image: digitalocean.com/php
    container_name: app
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./.docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  server:
    image: nginx:alpine
    container_name: server
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  #PostgreSQL Service
  db:
    image: postgres:alpine
    container_name: db
    tty: true
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      SERVICE_NAME: postgres
    volumes:
      - dbdata:/var/lib/postgres
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
volumes:
  dbdata:
    driver: local